config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#main'
  get 'recipes/:name', to: 'recipes#show', as: 'recipe'
  get 'recipes', to: 'recipes#index', as: 'recipes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
require './lib/edamam_api_wrapper'
require './lib/recipe'
class RecipesController < ApplicationController
  def index
    @search = params[:search]
    @recipes = EdamamApiWrapper.list_recipes(@search)

    if @search == ""
      flash[:message] = "Must put words in the Search bar.  How about 'cake'?"
      flash[:status] = "error"
      redirect_to root_path
    elsif @recipes.empty?
      flash[:message] = "No Results"
      flash[:status] = "error"
      redirect_to root_path
    else
      @paginatable_recipes = Kaminari.paginate_array(@recipes).page(params[:page]).per(10)
    end

  end

  def show
    @uri = params[:name]
    @recipe = EdamamApiWrapper.find_recipe(@uri)
    if @recipe == "Empty Array or nil in data_parsed"
      flash[:message] = "Oops, there is no recipe."
      flash[:status] = "error"
      redirect_to root_path
    else
      flash[:status] = :success
    end
    @recipe
  end

  def main
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>

<nav class="top-bar" data-topbar>

  <div class="top-bar-left small-up-1 large-up-2">

    <ul class="title-area small-up-6 large-up-6">
      <li class="name">
        <%= link_to root_path, :class => 'home-button' do %>
        <span class="nav-icon">
          <i class="fa fa-home"></i>
        </span>
        <span class="nav-text">
          Home
        </span>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="top-bar-section small-up-2 large-up-6">

    <button class="button nav-button small-up-6 large-up-6" type="button" data-toggle="fancy-dropdown">Fancy Dishes</button>
    <div class="dropdown-pane" id="fancy-dropdown" data-dropdown data-auto-focus="true">
      Impress everyone you know.
      <ul>
        <li> <%= link_to "Beef Wellington", recipes_path(:search => 'beef wellington') %></li>
        <li> <%= link_to "Chicken Cordon Bleu", recipes_path(:search => 'Chicken Cordon Bleu') %> </li>
        <li><%= link_to "Crudités", recipes_path(:search => 'Crudites') %></li>
      </ul>
    </div>


    <button class="button nav-button small-up-6 large-up-6" type="button" data-toggle="meals-dropdown">Meal</button>
    <div class="dropdown-pane" id="meals-dropdown" data-dropdown data-auto-focus="true">
      All the meals.
      <ul>
        <li><%= link_to "Breakfast", recipes_path(:search => 'Breakfast') %></li>
        <li><%= link_to "Lunch", recipes_path(:search => 'Lunch') %></li>
        <li><%= link_to "Dinner", recipes_path(:search => 'Dinner') %></li>
        <li><%= link_to "Dessert", recipes_path(:search => 'Dessert') %></li>
        <li><%= link_to "Snacks", recipes_path(:search => 'Snacks') %></li>
      </ul>
    </div>

    <button class="button nav-button small-up-6 large-up-6" type="button" data-toggle="cheap-dropdown">Cheap Ingredients</button>
      <div class="dropdown-pane" id="cheap-dropdown" data-dropdown data-auto-focus="true">
      Get the most out of your money.
        <ul>
          <li><%= link_to "Flour", recipes_path(:search => 'Flour') %></li>
          <li><%= link_to "Eggs", recipes_path(:search => 'Eggs') %></li>
          <li><%= link_to "Rice", recipes_path(:search => 'Rice') %></li>
          <li><%= link_to "Beans", recipes_path(:search => 'Beans') %></li>
          </ul>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Yum Yum" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Yum Yum" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="top-words">
    <h1 class = "big-title"><em><%= link_to 'Yum Yum', root_path %></em></h1>
      </div>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer>
      <div class="wrap-row small-up-1">
        <div class="edamam">
        <p class="edamam">Powered by Edamam</p>
          </div>
      </div>
    </footer>
  </body>
</html>

app/views/recipes/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Yum Yum</title>
</head>
<body>
  <%# Show all of the fancy recipes here %>
  <div class="container-index">


  <div class="wrap row small-up-1 medium-up-2 large-up-5 background-index">

    <% @paginatable_recipes.each do |recipe| %>
      <div class="column food-block">
        <% params[:uri] = recipe.uri[/recipe_.*/] %>
        <h3 class = "recipe-name"><%= link_to recipe.name, recipe_path(params[:uri]) %></h3>
        <% recipe.image %>
        <%= link_to recipe_path(params[:uri]) do %>
        <img class = "food-image" src="<%=recipe.image %>" alt= "<%= recipe.name %>">
        <% end %>
      </div>
    <% end %>
  </div>

      <div class="page-list">
        <%= paginate @paginatable_recipes %>
      </div>
    </div>
</body>
</html>

app/views/recipes/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <section class = "box-around-search">
    <div class="searcher">
      <%= form_tag('/recipes', method: "get") do %>
      <%= text_field_tag :search, params[:search], class: "search-bar"%>
      <%= submit_tag("Search", class: "button search-button")%>
      <% end %>
    </div>
  </section>
</body>
</html>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <%# show one recipe here %>
  <div class="row top-block-title-image">

    <section class = "recipe-image small-12 medium-6 large-6 column">
      <img src=<%=@recipe.image %> alt=<%= @recipe.name %>>
      <div class="recipe-link">
        <a href="<%= @recipe.url %>">Full Recipe </a>
      </div>
    </section>

    <div class="columns recipe-name column-block small-12 medium-6 large-6">
      <h1 class = "recipe-header"><%= @recipe.name %></h1>
    </div>
  </div>



  <div class="wrap row small-up-1 medium-up-2 large-up-3">

    <section class = "ingredients column">
      <h3>Ingredients</h3>
      <ul>
        <% @recipe.ingredients.each do |ingredient| %>
        <li><%= ingredient %></li>
        <% end %>
      </ul>
    </section>



    <section class = "nutrients column">
      <table class="hover">
        <thead>
          <th width="200">Nutrition Information</th>
          <th width="150"></th>
        </thead>
        <tbody>


          <% @recipe.nutrient_info.each do |info| %>
          <tr>
            <td><%= info[1]['label']%></td>
            <td><%= info[1]['quantity'].round(2)%></td>
          </tr>
        </th>
        <% end %>
      </tbody>

    </table>
  </section>

  <section class = "health-labels column">
    <h3>Health Labels</h3>
    <ul>
      <% @recipe.health_labels.each do |health_label| %>
      <li>
        <span class="nav-icon">
          <i class="fa fa-heart-o"></i>
        </span>
        <span><%= health_label %></span>
      </li>
      <% end %>
    </ul>
  </section>
</div>

</body>
</html>